[package]
name = "rabbitsay"
version = "0.1.0"
edition = "2021"

[lib]
name = "rabbitsay"
path = "src/lib.rs"

[[bin]]
name = "rabbitsay"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
